"""Durable multi-instance callback outbox on the RLS control plane.

Revision ID: 0005_postgres_outbox
Revises: 0004_runtime_privilege_boundary
Create Date: 2026-07-13

Provisional numbering: if Stripe PR C takes 0005, rename this revision to 0006
and point down_revision at C's migration before either PR merges.
"""
from __future__ import annotations

from alembic import op

revision = "0005_postgres_outbox"
down_revision = "0004_runtime_privilege_boundary"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        r"""
        CREATE TABLE public.queued_actions (
          org_id uuid NOT NULL REFERENCES public.orgs(id) ON DELETE CASCADE,
          bot_id text NOT NULL,
          action_id text NOT NULL,
          action text NOT NULL,
          owner text NOT NULL DEFAULT '',
          due text NOT NULL DEFAULT '',
          source_event_key text NOT NULL DEFAULT '',
          source_fingerprint text NOT NULL DEFAULT '',
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now(),
          PRIMARY KEY (org_id, action_id)
        );
        CREATE INDEX idx_queued_actions_bot
          ON public.queued_actions(org_id, bot_id, created_at, action_id);
        CREATE UNIQUE INDEX uq_queued_actions_source_event
          ON public.queued_actions(org_id, source_event_key)
          WHERE source_event_key <> '';
        CREATE INDEX idx_queued_actions_fingerprint
          ON public.queued_actions(
            org_id, bot_id, source_fingerprint, created_at DESC
          )
          WHERE source_fingerprint <> '';

        CREATE TABLE public.callback_outbox (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          org_id uuid NOT NULL REFERENCES public.orgs(id) ON DELETE CASCADE,
          idempotency_key text NOT NULL,
          bot_id text NOT NULL,
          action_id text NOT NULL DEFAULT '',
          event text NOT NULL
            CHECK (event IN ('action.requested', 'session.ended')),
          callback_url text NOT NULL,
          team_id text NOT NULL DEFAULT '',
          channel text NOT NULL DEFAULT '',
          external_ref_json jsonb NOT NULL DEFAULT '{}'::jsonb,
          payload_json jsonb NOT NULL,
          status text NOT NULL DEFAULT 'pending'
            CHECK (status IN ('pending', 'sending', 'failed', 'delivered')),
          attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
          next_attempt_at timestamptz,
          lease_token uuid,
          lease_until timestamptz,
          last_error text NOT NULL DEFAULT '',
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now(),
          delivered_at timestamptz,
          UNIQUE (org_id, idempotency_key)
        );
        CREATE INDEX idx_callback_outbox_due
          ON public.callback_outbox(next_attempt_at, id)
          WHERE status IN ('pending', 'failed') AND next_attempt_at IS NOT NULL;
        CREATE INDEX idx_callback_outbox_lease
          ON public.callback_outbox(lease_until, id)
          WHERE status = 'sending';
        CREATE INDEX idx_callback_outbox_org
          ON public.callback_outbox(org_id, created_at DESC, id DESC);

        ALTER TABLE public.queued_actions ENABLE ROW LEVEL SECURITY;
        ALTER TABLE public.queued_actions FORCE ROW LEVEL SECURITY;
        CREATE POLICY tenant_isolation ON public.queued_actions
          TO laura_app
          USING (
            org_id = NULLIF(
              current_setting('app.current_org', true), ''
            )::uuid
          )
          WITH CHECK (
            org_id = NULLIF(
              current_setting('app.current_org', true), ''
            )::uuid
          );

        ALTER TABLE public.callback_outbox ENABLE ROW LEVEL SECURITY;
        ALTER TABLE public.callback_outbox FORCE ROW LEVEL SECURITY;
        CREATE POLICY tenant_isolation ON public.callback_outbox
          TO laura_app
          USING (
            org_id = NULLIF(
              current_setting('app.current_org', true), ''
            )::uuid
          )
          WITH CHECK (
            org_id = NULLIF(
              current_setting('app.current_org', true), ''
            )::uuid
          );

        -- The multi-instance worker needs to discover which tenants have due
        -- work after a restart, but does not need a cross-tenant payload read.
        -- Return UUIDs only; payload claim/read remains under ordinary RLS.
        CREATE OR REPLACE FUNCTION laura_private.due_callback_orgs(
          p_limit integer DEFAULT 20
        )
        RETURNS SETOF uuid
        LANGUAGE sql
        VOLATILE
        SECURITY DEFINER
        SET search_path = ''
        AS $function$
          SELECT o.org_id
            FROM public.callback_outbox AS o
           WHERE (
             o.status IN ('pending', 'failed')
             AND o.next_attempt_at IS NOT NULL
             AND o.next_attempt_at <= pg_catalog.clock_timestamp()
           ) OR (
             o.status = 'sending'
             AND o.lease_until IS NOT NULL
             AND o.lease_until <= pg_catalog.clock_timestamp()
           )
           GROUP BY o.org_id
           ORDER BY min(
             CASE WHEN o.status = 'sending'
                  THEN o.lease_until ELSE o.next_attempt_at END
           ), o.org_id
           LIMIT LEAST(GREATEST(COALESCE(p_limit, 20), 1), 100)
        $function$;

        REVOKE ALL ON TABLE public.queued_actions,
          public.callback_outbox FROM PUBLIC;
        REVOKE ALL ON SEQUENCE public.callback_outbox_id_seq FROM PUBLIC;
        REVOKE ALL ON FUNCTION
          laura_private.due_callback_orgs(integer) FROM PUBLIC;

        DO $roles$
        BEGIN
          IF EXISTS (
            SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'anon'
          ) THEN
            REVOKE ALL ON TABLE public.queued_actions,
              public.callback_outbox FROM anon;
            REVOKE ALL ON SEQUENCE
              public.callback_outbox_id_seq FROM anon;
            REVOKE ALL ON FUNCTION
              laura_private.due_callback_orgs(integer) FROM anon;
          END IF;
          IF EXISTS (
            SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'authenticated'
          ) THEN
            REVOKE ALL ON TABLE public.queued_actions,
              public.callback_outbox FROM authenticated;
            REVOKE ALL ON SEQUENCE
              public.callback_outbox_id_seq FROM authenticated;
            REVOKE ALL ON FUNCTION
              laura_private.due_callback_orgs(integer) FROM authenticated;
          END IF;
        END
        $roles$;

        REVOKE ALL ON TABLE public.queued_actions,
          public.callback_outbox FROM laura_app;
        REVOKE ALL ON SEQUENCE
          public.callback_outbox_id_seq FROM laura_app;
        GRANT SELECT, INSERT, UPDATE ON TABLE
          public.queued_actions, public.callback_outbox TO laura_app;
        GRANT USAGE ON SEQUENCE
          public.callback_outbox_id_seq TO laura_app;
        GRANT EXECUTE ON FUNCTION
          laura_private.due_callback_orgs(integer) TO laura_app;
        """
    )


def downgrade() -> None:
    raise NotImplementedError(
        "0005 is the durable callback boundary; replace it with a reviewed "
        "forward migration instead of returning production delivery to SQLite."
    )
