"""Durable Company Brain (M1): org-owned knowledge sources on the RLS plane.

Revision ID: 0010_company_brain
Revises: 0009_canonical_actions
Create Date: 2026-07-17

The retrieval seam already exists (rag.py per-org index files merged into
retrieve(org_id=...)); what never existed is the INGESTION side and a durable
home for customer documents. These tables are that home:

- ``knowledge_sources``: an org's connected source (upload | drive)
- ``knowledge_documents``: one file/document inside a source
- ``knowledge_document_versions``: immutable extracted text per version
                               (new content ⇒ new version, dedup by checksum)
- ``knowledge_chunks``: retrieval units + a generated tsvector for
                               keyword search (the FTS half of hybrid search)
- ``knowledge_assignments``: which avatars may retrieve a source
- ``knowledge_sync_jobs``: claim/lease ingestion jobs (the callback_outbox
                               worker pattern; nothing runs on the live path)

The per-(org, avatar) index files that the live path ranks in memory are
REBUILT from these tables (ingest + boot), which closes the pre-M1 durability
gap where org indexes died with the App Runner disk.

Deliberate deviation from the no-DELETE grant convention: ``laura_app`` gets
DELETE on ``knowledge_chunks`` (and only there); deleting a source must
remove retrievability, and chunks are derived data always rebuildable from
their document version. Sources/documents themselves tombstone via status.

Everything else follows 0006/0009 discipline: FORCE RLS with the NULLIF
``app.current_org`` policy TO laura_app, REVOKE-then-GRANT, and a
SECURITY DEFINER discovery function that returns org UUIDs only.
"""
from __future__ import annotations

from alembic import op

revision = "0010_company_brain"
down_revision = "0009_canonical_actions"
branch_labels = None
depends_on = None

_TENANT_TABLES = (
    "knowledge_sources",
    "knowledge_documents",
    "knowledge_document_versions",
    "knowledge_chunks",
    "knowledge_assignments",
    "knowledge_sync_jobs",
)


def upgrade() -> None:
    op.execute(
        r"""
        CREATE TABLE public.knowledge_sources (
          org_id uuid NOT NULL REFERENCES public.orgs(id) ON DELETE CASCADE,
          id uuid NOT NULL DEFAULT gen_random_uuid(),
          name text NOT NULL,
          kind text NOT NULL CHECK (kind IN ('upload', 'drive')),
          status text NOT NULL DEFAULT 'active'
            CHECK (status IN ('active', 'deleted')),
          drive_folder_id text NOT NULL DEFAULT '',
          embedding_provider text NOT NULL DEFAULT '',
          embedding_model text NOT NULL DEFAULT '',
          embedding_dim integer NOT NULL DEFAULT 0,
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now(),
          deleted_at timestamptz,
          PRIMARY KEY (org_id, id)
        );

        CREATE TABLE public.knowledge_documents (
          org_id uuid NOT NULL REFERENCES public.orgs(id) ON DELETE CASCADE,
          id uuid NOT NULL DEFAULT gen_random_uuid(),
          source_id uuid NOT NULL,
          filename text NOT NULL,
          mime text NOT NULL DEFAULT '',
          size_bytes bigint NOT NULL DEFAULT 0,
          checksum text NOT NULL DEFAULT '',
          storage_ref text NOT NULL DEFAULT '',
          status text NOT NULL DEFAULT 'pending'
            CHECK (status IN ('pending', 'published', 'failed', 'deleted')),
          error text NOT NULL DEFAULT '',
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now(),
          PRIMARY KEY (org_id, id),
          FOREIGN KEY (org_id, source_id)
            REFERENCES public.knowledge_sources(org_id, id) ON DELETE CASCADE
        );
        CREATE INDEX idx_knowledge_documents_source
          ON public.knowledge_documents(org_id, source_id, created_at DESC);

        CREATE TABLE public.knowledge_document_versions (
          org_id uuid NOT NULL REFERENCES public.orgs(id) ON DELETE CASCADE,
          id uuid NOT NULL DEFAULT gen_random_uuid(),
          document_id uuid NOT NULL,
          version integer NOT NULL,
          checksum text NOT NULL DEFAULT '',
          extracted_chars integer NOT NULL DEFAULT 0,
          text_content text NOT NULL DEFAULT '',
          created_at timestamptz NOT NULL DEFAULT now(),
          PRIMARY KEY (org_id, id),
          UNIQUE (org_id, document_id, version),
          FOREIGN KEY (org_id, document_id)
            REFERENCES public.knowledge_documents(org_id, id) ON DELETE CASCADE
        );

        CREATE TABLE public.knowledge_chunks (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          org_id uuid NOT NULL REFERENCES public.orgs(id) ON DELETE CASCADE,
          source_id uuid NOT NULL,
          document_id uuid NOT NULL,
          version_id uuid NOT NULL,
          seq integer NOT NULL DEFAULT 0,
          source_name text NOT NULL DEFAULT '',
          section text NOT NULL DEFAULT '',
          text text NOT NULL,
          fts tsvector GENERATED ALWAYS AS (to_tsvector('simple', text)) STORED,
          created_at timestamptz NOT NULL DEFAULT now(),
          FOREIGN KEY (org_id, version_id)
            REFERENCES public.knowledge_document_versions(org_id, id)
            ON DELETE CASCADE
        );
        CREATE INDEX idx_knowledge_chunks_org_source
          ON public.knowledge_chunks(org_id, source_id, document_id, seq);
        CREATE INDEX idx_knowledge_chunks_fts
          ON public.knowledge_chunks USING GIN (fts);

        CREATE TABLE public.knowledge_assignments (
          org_id uuid NOT NULL REFERENCES public.orgs(id) ON DELETE CASCADE,
          source_id uuid NOT NULL,
          avatar_id text NOT NULL,
          created_at timestamptz NOT NULL DEFAULT now(),
          PRIMARY KEY (org_id, source_id, avatar_id),
          FOREIGN KEY (org_id, source_id)
            REFERENCES public.knowledge_sources(org_id, id) ON DELETE CASCADE
        );

        CREATE TABLE public.knowledge_sync_jobs (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          org_id uuid NOT NULL REFERENCES public.orgs(id) ON DELETE CASCADE,
          source_id uuid NOT NULL,
          document_id uuid,
          kind text NOT NULL
            CHECK (kind IN ('ingest_document', 'rebuild_index', 'sync_drive')),
          status text NOT NULL DEFAULT 'pending'
            CHECK (status IN ('pending', 'running', 'done', 'failed')),
          attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
          next_attempt_at timestamptz DEFAULT now(),
          lease_token uuid,
          lease_until timestamptz,
          last_error text NOT NULL DEFAULT '',
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now()
        );
        CREATE INDEX idx_knowledge_jobs_due
          ON public.knowledge_sync_jobs(next_attempt_at, id)
          WHERE status IN ('pending', 'failed') AND next_attempt_at IS NOT NULL;
        CREATE INDEX idx_knowledge_jobs_lease
          ON public.knowledge_sync_jobs(lease_until, id)
          WHERE status = 'running';
        CREATE INDEX idx_knowledge_jobs_org
          ON public.knowledge_sync_jobs(org_id, created_at DESC, id DESC);
        """
    )

    for table in _TENANT_TABLES:
        op.execute(
            f"""
            ALTER TABLE public.{table} ENABLE ROW LEVEL SECURITY;
            ALTER TABLE public.{table} FORCE ROW LEVEL SECURITY;
            CREATE POLICY tenant_isolation ON public.{table}
              TO laura_app
              USING (
                org_id = NULLIF(
                  current_setting('app.current_org', true), ''
                )::uuid
              )
              WITH CHECK (
                org_id = NULLIF(
                  current_setting('app.current_org', true), ''
                )::uuid
              );
            """
        )

    op.execute(
        r"""
        -- Workers must discover which tenants have due ingest work after a
        -- restart without any cross-tenant payload read: UUIDs only, exactly
        -- the due_callback_orgs shape from 0006.
        CREATE OR REPLACE FUNCTION laura_private.due_knowledge_orgs(
          p_limit integer DEFAULT 20
        )
        RETURNS SETOF uuid
        LANGUAGE sql
        VOLATILE
        SECURITY DEFINER
        SET search_path = ''
        AS $function$
          SELECT j.org_id
            FROM public.knowledge_sync_jobs AS j
           WHERE (
             j.status IN ('pending', 'failed')
             AND j.next_attempt_at IS NOT NULL
             AND j.next_attempt_at <= pg_catalog.clock_timestamp()
           ) OR (
             j.status = 'running'
             AND j.lease_until IS NOT NULL
             AND j.lease_until <= pg_catalog.clock_timestamp()
           )
           GROUP BY j.org_id
           ORDER BY min(
             CASE WHEN j.status = 'running'
                  THEN j.lease_until ELSE j.next_attempt_at END
           ), j.org_id
           LIMIT LEAST(GREATEST(COALESCE(p_limit, 20), 1), 100)
        $function$;

        -- Boot-time index regeneration needs the orgs that HAVE published
        -- chunks (their in-memory index files may have died with the disk).
        CREATE OR REPLACE FUNCTION laura_private.knowledge_index_orgs(
          p_limit integer DEFAULT 200
        )
        RETURNS SETOF uuid
        LANGUAGE sql
        STABLE
        SECURITY DEFINER
        SET search_path = ''
        AS $function$
          SELECT DISTINCT c.org_id
            FROM public.knowledge_chunks AS c
           LIMIT LEAST(GREATEST(COALESCE(p_limit, 200), 1), 1000)
        $function$;

        REVOKE ALL ON TABLE
          public.knowledge_sources,
          public.knowledge_documents,
          public.knowledge_document_versions,
          public.knowledge_chunks,
          public.knowledge_assignments,
          public.knowledge_sync_jobs
        FROM PUBLIC;
        REVOKE ALL ON SEQUENCE
          public.knowledge_chunks_id_seq,
          public.knowledge_sync_jobs_id_seq
        FROM PUBLIC;
        REVOKE ALL ON FUNCTION
          laura_private.due_knowledge_orgs(integer),
          laura_private.knowledge_index_orgs(integer)
        FROM PUBLIC;

        DO $roles$
        BEGIN
          IF EXISTS (
            SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'anon'
          ) THEN
            REVOKE ALL ON TABLE
              public.knowledge_sources, public.knowledge_documents,
              public.knowledge_document_versions, public.knowledge_chunks,
              public.knowledge_assignments, public.knowledge_sync_jobs
            FROM anon;
            REVOKE ALL ON SEQUENCE
              public.knowledge_chunks_id_seq,
              public.knowledge_sync_jobs_id_seq FROM anon;
            REVOKE ALL ON FUNCTION
              laura_private.due_knowledge_orgs(integer),
              laura_private.knowledge_index_orgs(integer) FROM anon;
          END IF;
          IF EXISTS (
            SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'authenticated'
          ) THEN
            REVOKE ALL ON TABLE
              public.knowledge_sources, public.knowledge_documents,
              public.knowledge_document_versions, public.knowledge_chunks,
              public.knowledge_assignments, public.knowledge_sync_jobs
            FROM authenticated;
            REVOKE ALL ON SEQUENCE
              public.knowledge_chunks_id_seq,
              public.knowledge_sync_jobs_id_seq FROM authenticated;
            REVOKE ALL ON FUNCTION
              laura_private.due_knowledge_orgs(integer),
              laura_private.knowledge_index_orgs(integer) FROM authenticated;
          END IF;
        END
        $roles$;

        REVOKE ALL ON TABLE
          public.knowledge_sources, public.knowledge_documents,
          public.knowledge_document_versions, public.knowledge_chunks,
          public.knowledge_assignments, public.knowledge_sync_jobs
        FROM laura_app;
        REVOKE ALL ON SEQUENCE
          public.knowledge_chunks_id_seq,
          public.knowledge_sync_jobs_id_seq FROM laura_app;
        GRANT SELECT, INSERT, UPDATE ON TABLE
          public.knowledge_sources, public.knowledge_documents,
          public.knowledge_document_versions, public.knowledge_assignments,
          public.knowledge_sync_jobs TO laura_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE
          public.knowledge_chunks TO laura_app;
        GRANT USAGE ON SEQUENCE
          public.knowledge_chunks_id_seq,
          public.knowledge_sync_jobs_id_seq TO laura_app;
        GRANT EXECUTE ON FUNCTION
          laura_private.due_knowledge_orgs(integer),
          laura_private.knowledge_index_orgs(integer) TO laura_app;
        """
    )


def downgrade() -> None:
    raise NotImplementedError(
        "0010 is the durable Company Brain boundary; write a reviewed forward "
        "migration instead of dropping customer knowledge."
    )
