"""Meeting Memory Slice 2: the graph half — edges, chunks, grants, visibility.

Revision ID: 0025_meeting_memory_graph
Revises: 0024_meeting_memory
Create Date: 2026-07-30

docs/company-brain/MEETING-MEMORY-SPEC.md §5/§7/§8.3. Slice 1 (0024) made
meetings accumulate; this makes them RECALLABLE and LINKED:

- ``memory_chunks``  — distilled meeting text chunked + provider-stamped
                       embeddings + generated FTS, feeding the mid-meeting
                       ``meeting_memory_search`` tool. Self-contained in the
                       memory plane (never the avatar file index, never
                       ``knowledge_*``), so the un-ACL'd retrieval paths
                       cannot reach meeting content by construction.
- ``memory_edges``   — entity relations witnessed by a meeting
                       (attended/decided/owns/mentions/…), idempotent PK.
- ``memory_grants``  — ADMIN-GRANTED per-meeting access for named people
                       (owner-ratified rule 2026-07-30: all-attendees +
                       org-public opt-in + admin grants). Additive, audited
                       by the caller, never a blanket person-wide grant.
- ``memory_meetings.visibility`` — 'attendees' (default) | 'org-public'.
"""
from __future__ import annotations

from alembic import op

revision = "0025_meeting_memory_graph"
down_revision = "0024_meeting_memory"
branch_labels = None
depends_on = None

_NEW_TENANT_TABLES = (
    "memory_chunks",
    "memory_edges",
    "memory_grants",
)


def upgrade() -> None:
    op.execute(
        r"""
        ALTER TABLE public.memory_meetings
          ADD COLUMN visibility text NOT NULL DEFAULT 'attendees'
            CHECK (visibility IN ('attendees', 'org-public'));

        CREATE TABLE public.memory_chunks (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          org_id uuid NOT NULL REFERENCES public.orgs(id) ON DELETE CASCADE,
          meeting_id uuid NOT NULL,
          idx integer NOT NULL DEFAULT 0,
          text text NOT NULL DEFAULT '',
          embedding_provider text NOT NULL DEFAULT '',
          embedding_json text NOT NULL DEFAULT '',
          fts tsvector GENERATED ALWAYS AS (to_tsvector('simple', text)) STORED,
          created_at timestamptz NOT NULL DEFAULT now(),
          UNIQUE (org_id, meeting_id, idx),
          FOREIGN KEY (org_id, meeting_id)
            REFERENCES public.memory_meetings(org_id, id) ON DELETE CASCADE
        );
        CREATE INDEX idx_memory_chunks_fts
          ON public.memory_chunks USING GIN (fts);
        CREATE INDEX idx_memory_chunks_meeting
          ON public.memory_chunks(org_id, meeting_id);

        CREATE TABLE public.memory_edges (
          org_id uuid NOT NULL REFERENCES public.orgs(id) ON DELETE CASCADE,
          src_id uuid NOT NULL,
          dst_id uuid NOT NULL,
          rel text NOT NULL CHECK (rel IN
            ('attended', 'decided', 'owns', 'mentions', 'about',
             'produced', 'follows_up')),
          meeting_id uuid NOT NULL,
          confidence real NOT NULL DEFAULT 1.0,
          created_at timestamptz NOT NULL DEFAULT now(),
          PRIMARY KEY (org_id, src_id, rel, dst_id, meeting_id),
          FOREIGN KEY (org_id, src_id)
            REFERENCES public.memory_entities(org_id, id) ON DELETE CASCADE,
          FOREIGN KEY (org_id, dst_id)
            REFERENCES public.memory_entities(org_id, id) ON DELETE CASCADE,
          FOREIGN KEY (org_id, meeting_id)
            REFERENCES public.memory_meetings(org_id, id) ON DELETE CASCADE
        );
        CREATE INDEX idx_memory_edges_dst
          ON public.memory_edges(org_id, dst_id, rel);
        CREATE INDEX idx_memory_edges_meeting
          ON public.memory_edges(org_id, meeting_id);

        CREATE TABLE public.memory_grants (
          org_id uuid NOT NULL REFERENCES public.orgs(id) ON DELETE CASCADE,
          meeting_id uuid NOT NULL,
          entity_id uuid NOT NULL,
          granted_by text NOT NULL DEFAULT '',
          created_at timestamptz NOT NULL DEFAULT now(),
          PRIMARY KEY (org_id, meeting_id, entity_id),
          FOREIGN KEY (org_id, meeting_id)
            REFERENCES public.memory_meetings(org_id, id) ON DELETE CASCADE,
          FOREIGN KEY (org_id, entity_id)
            REFERENCES public.memory_entities(org_id, id) ON DELETE CASCADE
        );
        CREATE INDEX idx_memory_grants_entity
          ON public.memory_grants(org_id, entity_id);
        """
    )

    for table in _NEW_TENANT_TABLES:
        op.execute(
            f"""
            ALTER TABLE public.{table} ENABLE ROW LEVEL SECURITY;
            ALTER TABLE public.{table} FORCE ROW LEVEL SECURITY;
            CREATE POLICY tenant_isolation ON public.{table}
              TO laura_app
              USING (
                org_id = NULLIF(
                  current_setting('app.current_org', true), ''
                )::uuid
              )
              WITH CHECK (
                org_id = NULLIF(
                  current_setting('app.current_org', true), ''
                )::uuid
              );
            """
        )

    op.execute(
        r"""
        REVOKE ALL ON TABLE
          public.memory_chunks, public.memory_edges, public.memory_grants
        FROM PUBLIC;
        REVOKE ALL ON SEQUENCE public.memory_chunks_id_seq FROM PUBLIC;

        DO $roles$
        BEGIN
          IF EXISTS (
            SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'anon'
          ) THEN
            REVOKE ALL ON TABLE
              public.memory_chunks, public.memory_edges, public.memory_grants
            FROM anon;
            REVOKE ALL ON SEQUENCE public.memory_chunks_id_seq FROM anon;
          END IF;
          IF EXISTS (
            SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'authenticated'
          ) THEN
            REVOKE ALL ON TABLE
              public.memory_chunks, public.memory_edges, public.memory_grants
            FROM authenticated;
            REVOKE ALL ON SEQUENCE
              public.memory_chunks_id_seq FROM authenticated;
          END IF;
        END
        $roles$;

        REVOKE ALL ON TABLE
          public.memory_chunks, public.memory_edges, public.memory_grants
        FROM laura_app;
        REVOKE ALL ON SEQUENCE public.memory_chunks_id_seq FROM laura_app;
        -- Derived/replaceable tier (re-deposit replaces chunks/edges; Slice-3
        -- compaction and 'forget this meeting' delete them).
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE
          public.memory_chunks, public.memory_edges, public.memory_grants
          TO laura_app;
        GRANT USAGE ON SEQUENCE public.memory_chunks_id_seq TO laura_app;
        """
    )


def downgrade() -> None:
    raise NotImplementedError(
        "0025 holds accumulated meeting memory; write a reviewed forward "
        "migration instead of dropping it."
    )
